services:

  app:
    build: .
    container_name: pres_assistant_v2_app
    ports:
      - "8082:8082"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TELEGRAM_BOT_USERNAME: ${TELEGRAM_BOT_USERNAME:-asisstant_for_lecture_bot}
      HOST_USERPROFILE: "${USERPROFILE}"
    volumes:
      - h2_data:/app/data
      - ${USERPROFILE}:/mnt/userprofile:ro

  addin:
    build: ./pres-assistant-addin
    container_name: pres_assistant_v2_addin
    ports:
      - "3000:3000"
    environment:
      DOCKER: "true"
    volumes:
      # Монтируем сертификаты с хоста чтобы PowerPoint доверял HTTPS
      - ${USERPROFILE}/.office-addin-dev-certs:/root/.office-addin-dev-certs:ro

volumes:
  h2_data:
