spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/pres_assistant_v2}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

server.port=8082

telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
telegram.bot.username=${TELEGRAM_BOT_USERNAME:asisstant_for_lecture_bot}

spring.config.import=optional:file:./secrets.properties